name: lily-env - test and publish

on: push

jobs:
  test-and-push:
    name: Unit Tests - working branch
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        working-directory: .
        run: |
          pip install -r requirements.txt
          pip install -r test-requirements.txt

      - name: Launch tests
        working-directory: .
        run: py.test --cov=./lily_env --cov-config .coveragerc -r w -s -vv tests

      # if launched from master branch, then build and publish to PyPI
      - name: Build and publish
        if: github.ref == 'refs/heads/master'
        working-directory: .
        run: |
          python setup.py sdist
          twine upload dist/*
